### ISSUE TITLE
Where do you put the files?

### ISSUE THREAD

**Issue by joshuaiz** [nyl-auster/reactpress#13]
This looks cool but I have no idea where to put the files:

- WordPress root?
- themes folder?
- in a plugin?
- somewhere else?

Thanks!

**Comment by yann-yinn** [comment]
Good question. You have several solutions : 
- create a "static" directory like explained here : https://github.com/zeit/next.js/#static-file-serving-eg-images
- from a component, you can import the filepath like this, with a relative path :

```jsx
import Logo from "../../images/hippogriff.png";
const Logo = () => (
  <img width="200px" src={Logo} />
);
```

**Comment by joshuaiz** [comment]
Sorry, I wasn't clear. I meant where to put *your* files, e.g. where is the best place to install this project in relation to a WordPress install?

If I have a local WP site set up, where would I put the reactpress project and run npm install?

Thanks!

**Comment by yann-yinn** [comment]
Oh i see. It's really up to you but in local, you could put it at the same level as your wordpress. ex: 
- www
  - wordpress_local
  - reactpress

You could also choose some naming like this: ( or whatever is meaningful for you )
- www
  - myproject_back
  - myproject_front

**Comment by joshuaiz** [comment]
Got it...thanks!!!
